---
title: "SWC Seminar Series Final Project"
author: "Eric D. Johnson"
date: "Thursday, March 19, 2015"
output: word_document
---

This is a simple analysis of some gapminder data for the SWC final project.


Look at this great Afghanistan data! The trend is all wack!

```{r, echo=FALSE}
dir <- getwd() #set dir to the current working directory

## Data read from .txt file and then subsetted
# data.in <- read.table("../data/gapminderDataFiveYear.txt", sep="\t", header = TRUE)
# 
# Afgstn.data <- subset(data.in, country=="Afghanistan", 
#               select=c(year, gdpPercap))
# 
# Zmbw.data <- subset(data.in, country=="Zimbabwe", 
#              select=c(year, gdpPercap))
# 
# US.data <- subset(data.in, country=="United States", 
#            select=c(year, gdpPercap))

#SQL queries
Afgstn.sql <- "SELECT GapminderDataFiveYear.year, GapminderDataFiveYear.gdpPercap
               FROM GapminderDataFiveYear
               WHERE (((GapminderDataFiveYear.country) = 'Afghanistan'))"

Zmbw.sql <- "SELECT GapminderDataFiveYear.year, GapminderDataFiveYear.gdpPercap
               FROM GapminderDataFiveYear
               WHERE (((GapminderDataFiveYear.country) = 'Zimbabwe'))"

US.sql <- "SELECT GapminderDataFiveYear.year, GapminderDataFiveYear.gdpPercap
               FROM GapminderDataFiveYear
               WHERE (((GapminderDataFiveYear.country) = 'United States'))"

Contnt.sql <- "SELECT GapminderDataFiveYear.continent, 
                    Avg(GapminderDataFiveYear.lifeExp) AS MeanLifeExp, 
                    Min(GapminderDataFiveYear.lifeExp) AS MinLifeExp, 
                    Max(GapminderDataFiveYear.lifeExp) AS MaxLifeExp
                FROM GapminderDataFiveYear
                GROUP BY GapminderDataFiveYear.continent"

world.sql <-"SELECT GapminderDataFiveYear.lifeExp
             FROM GapminderDataFiveYear"

#data queried from SQLite database
library("DBI")
library("RSQLite")
setwd("../data/") #set the working directory to the folder called "data" at the same level as the current working directory

db.conn <- dbConnect(SQLite(), dbname = "GapMinder.sqlite") #create a databae connection

Afgstn.data <- dbGetQuery(db.conn, Afgstn.sql)

Zmbw.data <- dbGetQuery(db.conn, Zmbw.sql)

US.data <- dbGetQuery(db.conn, US.sql)

Contnt.stats <- dbGetQuery(db.conn, Contnt.sql)

world.lifeExp <- dbGetQuery(db.conn, world.sql)

dbDisconnect(db.conn)

setwd(dir)##re-set the working directory

##Data queried from MS Access database 
##this code needs the 'Test' channel to be configured via ODBC on the local machine
# library(RODBC)
# db.channel<-odbcConnect("Test")
# odbcGetInfo(db.channel)
# 
# Afgstn.data <- sqlQuery(db.channel, Afgstn.sql)
# 
# Zmbw.data <- sqlQuery(db.channel, Zmbw.sql)
# 
# US.data <- sqlQuery(db.channel, US.sql)
# 
# close(db.channel)
# 

library(ggplot2)
print(ggplot(Afgstn.data, aes(x=year, y=gdpPercap)) +
        geom_point() +
        geom_smooth(method=lm) +
        ggtitle("Afghanistan"))
```

Look at this great United States data; the trend is bomb-diggity!

```{r, echo=FALSE}

print(ggplot(US.data, aes(x=year, y=gdpPercap)) +
  geom_point() +
  geom_smooth(method=lm) +
  ggtitle("United States"))

```

Look at this great Zimbabwe data; super gnar!

```{r, echo=FALSE}

print(ggplot(Zmbw.data, aes(x=year, y=gdpPercap)) +
  geom_point() +
  geom_smooth(method=lm) +
  ggtitle("Zimbabwe"))

```

Summary stats by continent... Buzzowga!

```{r kable, echo=FALSE}
library(knitr)
kable(Contnt.stats)
```


```{r xtable, results="asis", echo=FALSE}
#library(xtable)
#tab <- xtable(summary(Contnt.stats)$coef, digits=c(0, 2, 2, 2)
#print(tab, type="html")

```

Here is the global life expectancy. The second figure has really narrow bin widths!

```{r, echo=FALSE}
qplot(lifeExp, data=world.lifeExp, geom="histogram")

qplot(lifeExp, data=world.lifeExp, geom="histogram",binwidth = .5) 

```
